#!/bin/bash

usage() {
  echo "Usage: wmh_seg.sh -i <input_file> -o <output_file> [-g] [-pmb] [-v] [-b <batch_size>]"
  exit 1
}

input_file=""
output_file=""
use_gpu="False"
enable_pmb="False"
verbose="False"
batch=1

while getopts ":i:o:gpvb:" opt; do
  case ${opt} in
    i)
      input_file=${OPTARG}
      ;;
    o)
      output_file=${OPTARG}
      ;;
    g)
      use_gpu="True"
      ;;
    p)
      enable_pmb="True"
      ;;
    v)
      verbose="True"
      ;;
    b)
      batch=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done

if [[ -z $input_file || -z $output_file ]]; then
  echo "Error: Missing input or output path."
  usage
fi

echo "Input file: $input_file"
echo "Output file: $output_file"
echo "Use GPU: $use_gpu"
echo "Enable PMB: $enable_pmb"
echo "Verbose mode: $verbose"
echo "Inference batch size: $batch"

# Run wmh_pytorch.py script only if input and output paths are provided
if [[ -n $input_file && -n $output_file ]]; then
  wmh_pytorch.py "$input_file" "$output_file" "$use_gpu" "$wmh_seg_home" "$verbose" "$enable_pmb" "$batch"
fi
